### ISSUE TITLE
Temas de palestras para a GraphQL Conf BR 2019

### ISSUE THREAD

**Issue by nic** [graphql-brasil/conf#1]
## Quais temas vocês gostariam de ver nas palestras no GraphQL Conf BR?

Comente nessa issue com o tema que você gostaria que fosse abordado.

Votem com 👍 se gostarem de alguém tema já proposto, ou postem um novo tema se ainda não existir.

- Os temas sugeridos pela comunidade servem de guia para a submissão de apresentações na conferência
- *Call For Papers*: https://forms.gle/SWssb246dszjgYoA9

Participem do Slack (https://graphql-slack.now.sh). 👈  Tudo será anunciado lá primeiro.

> Vale aqui o [Código de Conduta da Conf](http://reactconfbr.com.br/files/react_conf_brasil-codigo_de_conduta.pdf) (mesmo da React Conf)

[Resultado parcial](https://most-voted.netlify.com/?issueUrl=https%3A%2F%2Fgithub.com%2Fgraphql-brasil%2Fconf%2Fissues%2F1) (tks @fdaciuk :clap:)

**Comment by nic** [comment]
Hasura

**Comment by nic** [comment]
Prisma

**Comment by nic** [comment]
Apollo

**Comment by nic** [comment]
GraphQL com Exilir

**Comment by nic** [comment]
GraphQL com Go

**Comment by nic** [comment]
GraphQL com PHP

**Comment by nic** [comment]
GraphQL com Python

**Comment by nic** [comment]
GraphQL com Ruby

**Comment by nic** [comment]
GraphQL com Vue

**Comment by nic** [comment]
GraphQL com React

**Comment by nic** [comment]
GraphQL com Angular

**Comment by nic** [comment]
GraphQL com .NET (C#)

**Comment by nic** [comment]
GraphQL com Node.JS

**Comment by nic** [comment]
GraphQL com Java

**Comment by nic** [comment]
GraphQL Subscriptions

**Comment by nic** [comment]
GraphQL com Haskell

**Comment by nic** [comment]
GraphQL com Clojure

**Comment by nic** [comment]
Dgraph

**Comment by nic** [comment]
GraphQL com PostgreSQL/CockroachDB

**Comment by nic** [comment]
GraphQL com MySQL/MariaDB

**Comment by nic** [comment]
GraphQL com MongoDB

**Comment by nic** [comment]
GraphQL com RethinkDB

**Comment by nic** [comment]
GraphQL com SOAP

**Comment by nic** [comment]
GraphQL com Oracle

**Comment by nic** [comment]
Graphcool

**Comment by nic** [comment]
GraphQL no Android (Java/Kotlin)

**Comment by nic** [comment]
GraphQL no iOS (Obj-C/Swift)

**Comment by nic** [comment]
GraphQL no React-Native

**Comment by nic** [comment]
GraphQL com PWA

**Comment by nic** [comment]
Relay

**Comment by felipe-ssilva** [comment]
GraphQL vs REST

**Comment by felipe-ssilva** [comment]
GraphQL e AWS AppSync

**Comment by felipe-ssilva** [comment]
GraphQL e WordPress

**Comment by nic** [comment]
```@defer```

**Comment by nic** [comment]
```@stream```

**Comment by nic** [comment]
```fragments```

**Comment by nic** [comment]
file upload/download (uploadables)

**Comment by nic** [comment]
data mask

**Comment by nic** [comment]
data colocation

**Comment by nic** [comment]
organização de código

**Comment by jgcmarins** [comment]
`ACL`, `viewerCanSee`, `Permissions`, `RBAC`

**Comment by jgcmarins** [comment]
GraphQL Middlewares

**Comment by jgcmarins** [comment]
Unity Tests (Queries, Mutations and Subscriptions)

**Comment by jgcmarins** [comment]
e2e Tests

**Comment by jgcmarins** [comment]
[Optimizing Your GraphQL Request Waterfalls](https://github.com/entria/graphql-optimizing)

**Comment by jgcmarins** [comment]
schema-first vs code-first

**Comment by jgcmarins** [comment]
GraphQL + Security

**Comment by jgcmarins** [comment]
GraphQL + Dataloader

**Comment by jgcmarins** [comment]
Validating GraphQL Mutations Input fields

**Comment by jgcmarins** [comment]
```tsx
throw new Error(string)
```
vs
```tsx
return { error: string }
```
vs
```tsx
return { errors: string[] }
```

**Comment by jgcmarins** [comment]
GraphQL Schema Stitching

**Comment by jgcmarins** [comment]
[GraphQL Pagination](https://graphql.org/learn/pagination/)

**Comment by jgcmarins** [comment]
GraphQL Arguments for Complex Filters

**Comment by fdaciuk** [comment]
GraphQL no Gatsby

**Comment by sebas5384** [comment]
Cache

**Comment by lucasconstantino** [comment]
Persisted queries

**Comment by silviolleite** [comment]
GraphQL + Django

**Comment by jgcmarins** [comment]
[GraphQL Spec](https://github.com/graphql/graphql-spec)

**Comment by jgcmarins** [comment]
[urql](https://github.com/FormidableLabs/urql)

**Comment by ronal2do** [comment]
Apollo Federation for GraphQL Microservices

**Comment by thecylax** [comment]
GraphQL resolver: sync vs async
